### ISSUE TITLE
[Help] onBindViewHolder passes absolutePosition = -1

### ISSUE THREAD

**Issue by kadymuhammad** [afollestad/sectioned-recyclerview#25]
I have a problem with the library which I can not fix. I do not know if this is a bug or there is something I am missing.
I have a recyclerView with 2 sections when section one has no item onBindViewHolder passes the absolute position with -1 .Is this a normal behavior ?
```
public class MainRVAdapter extends SectionedRecyclerViewAdapter<MainRVAdapter.Holder>
{
    private static final String TAG = MainRVAdapter.class.getSimpleName();

    private static final int SECTION_COUNT = 2;
    private static final int DIRECTORIES_SECTION = 0;
    private static final int FILES_SECTION = 1;
    private final MainFragment mainFragment;
    private List<MFile> mFileList;
    private int filesCount;
    private int directoriesCount;
    private final Context mContext;
    private final MainActivityMainRvCallback callback;

    public MainRVAdapter(MainFragment mainFragment, List<MFile> mFileList, int filesCount,
                         int directoriesCount, MainActivityMainRvCallback callback)
    {
        this.mainFragment = mainFragment;
        this.mFileList = mFileList;
        this.filesCount = filesCount;
        this.directoriesCount = directoriesCount;
        mContext = mainFragment.getContext();
        this.callback = callback;

        Log.d(TAG, "MainRVAdapter: listSize = " + mFileList.size() + ",filesCount = " + filesCount + ",directoriesCount=" + directoriesCount + "");

    }

    @Override
    public int getSectionCount()
    {
        return SECTION_COUNT;
    }

    @Override
    public int getItemCount(int section)
    {
        switch (section)
        {
            case DIRECTORIES_SECTION:
                return directoriesCount;
            case FILES_SECTION:
                return filesCount;
        }
        return -1;
    }

    @Override
    public void onBindHeaderViewHolder(Holder holder, int section)
    {
        switch (section)
        {
            case DIRECTORIES_SECTION:
                holder.header.setText(mContext.getString(R.string.directories));
                break;
            case FILES_SECTION:
                holder.header.setText(mContext.getString(R.string.files));
                break;
        }
    }

    @Override
    public void onBindViewHolder(Holder holder, int section, int relativePosition, int absolutePosition)
    {
        final MFile mFile = mFileList.get(absolutePosition);
        holder.icon.setImageResource(MFile.getIcon(mFile));
        holder.title.setText(mFile.getName());
        holder.lastModifiedDate.setText(mFile.getLastDateModified());
        holder.itemView.setOnClickListener(new View.OnClickListener()
        {
            @Override
            public void onClick(View view)
            {
                callback.onClick(mFile.getAbsolutePath());
            }
        });
    }

    @Override
    public Holder onCreateViewHolder(ViewGroup parent, int viewType)
    {
        int layout = -1;
        switch (viewType)
        {
            case VIEW_TYPE_HEADER:
                layout = R.layout.rv_main_header;
                break;
            case VIEW_TYPE_ITEM:
                layout = R.layout.rv_main_item;
                break;
        }
        LayoutInflater inflater = LayoutInflater.from(mContext);
        return new Holder(inflater.inflate(layout, parent, false));
    }

    public void updateAdapter(List<MFile> mFileList, int filesCount, int directoriesCount)
    {
        Log.d(TAG, "MainRVAdapter: listSize = " + mFileList.size() + ",filesCount = " + filesCount + ",directoriesCount=" + directoriesCount + "");
        this.mFileList = mFileList;
        this.filesCount = filesCount;
        this.directoriesCount = directoriesCount;
        notifyDataSetChanged();
    }

    static class Holder extends RecyclerView.ViewHolder
    {
        /*Non header*/
        ImageView icon, moreInfo;
        TextView title, lastModifiedDate, header;

        /*Header*/
        Holder(View itemView)
        {
            super(itemView);
            icon = (ImageView) itemView.findViewById(R.id.icon);
            moreInfo = (ImageView) itemView.findViewById(R.id.more_info);
            title = (TextView) itemView.findViewById(R.id.title);
            lastModifiedDate = (TextView) itemView.findViewById(R.id.last_modified_date);
            header = (TextView) itemView.findViewById(R.id.header);
        }
    }
} 
```

Log-cat
```
11-21 14:31:54.168 16649-16649/muhammad.ibrahim.alkady.files D/MainRVAdapter: updateAdapter: listSize = 1,filesCount = 1,directoriesCount=0
11-21 14:31:54.185 16649-16649/muhammad.ibrahim.alkady.files D/AndroidRuntime: Shutting down VM
11-21 14:31:54.186 16649-16649/muhammad.ibrahim.alkady.files E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: muhammad.ibrahim.alkady.files, PID: 16649
                                                                               java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
                                                                                   at java.util.ArrayList.get(ArrayList.java:413)
                                                                                   at muhammad.ibrahim.alkady.files.adapters.MainRVAdapter.onBindViewHolder(MainRVAdapter.java:90)
                                                                                   at muhammad.ibrahim.alkady.files.adapters.MainRVAdapter.onBindViewHolder(MainRVAdapter.java:26)
                                                                                   at com.afollestad.sectionedrecyclerview.SectionedRecyclerViewAdapter.onBindViewHolder(SectionedRecyclerViewAdapter.java:152)
                                                                                   at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6067)
                                                                                   at com.afollestad.sectionedrecyclerview.SectionedRecyclerViewAdapter.onBindViewHolder(SectionedRecyclerViewAdapter.java:167)
                                                                                   at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6100)
                                                                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5282)
                                                                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5158)
                                                                                   at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2061)
                                                                                   at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:562)
                                                                                   at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1408)
                                                                                   at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:580)
                                                                                   at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
                                                                                   at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3379)
                                                                                   at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3188)
                                                                                   at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3632)
                                                                                   at android.view.View.layout(View.java:17643)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                   at android.view.View.layout(View.java:17643)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                   at android.view.View.layout(View.java:17643)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                                   at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                                   at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                                   at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1367)
                                                                                   at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:849)
                                                                                   at android.view.View.layout(View.java:17643)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                   at android.view.View.layout(View.java:17643)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                   at android.view.View.layout(View.java:17643)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                                   at android.view.View.layout(View.java:17643)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                   at android.view.View.layout(View.java:17643)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
11-21 14:31:54.186 16649-16649/muhammad.ibrahim.alkady.files E/AndroidRuntime:     at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
                                                                                   at android.view.View.layout(View.java:17643)
                                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                                   at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2341)
                                                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6306)
                                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                   at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6088)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
 

 - Library version: `0.2.3`
 - Device OS version: `7.1`
 - Device Manufacturer: `Samsung`
 - Device Name: `S5`

**Comment by AkshayChordiya** [comment]
I am also facing this issue. Current workaround till @afollestad fixes it.

` if (absolutePosition == -1)
            return;`

**Comment by kadymuhammad** [comment]
@AkshayChordiya Thanks for your help.

**Comment by nadavfima** [comment]
Sometimes I get -2 as well., so...
`if (absolutePosition < 0) return;`

**Comment by AkshayChordiya** [comment]
@afollestad I rewrote the my logic of adapter and things seem to work perfect. I don't think it's a bug. 
My opinion of this bug is if the developer writes proper logic in `getItemCount(int section)` things should go fine.

**Comment by nadavfima** [comment]
I'll try to research some more. Thing is, it's not happening on my device - only for other people who use the app (not all of them)

**Comment by AkshayChordiya** [comment]
@nadavfima I was facing this same issue. But I refined my logic for `getItemCount(int section)` and the problem got solved.

**Comment by nadavfima** [comment]
@AkshayChordiya @kadymuhammad 

Indeed, all is fine with the library it seems. It was a bug with my section indexer class.
