### ISSUE TITLE
IndexOutOfBoundsException during scrolling through list

### ISSUE THREAD

**Issue by Xorok** [afollestad/sectioned-recyclerview#47]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of this library.
- [X] I have given my issue a non-generic title.

###### Include the following:
 - Library version: `0.4.4`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Android Emulator`
 - Device Name: `Nexus 5X base device`

Hi,
as I've written some days ago in issue https://github.com/afollestad/sectioned-recyclerview/issues/46, I recently updated from v0.4.1 to v0.4.4, and I think I've found another bug which started occuring in v0.4.2. When scrolling through the list, the app crashes towards the bottom with an IndexOutOfBoundsException, as absolutePosition (which should match the size of the entries list), grows to the total size of the list and therefore above the max index.

```java
@Override
public void onBindViewHolder(ViewHolder viewHolder, int section, int relativePosition, int absolutePosition) {
    // Setup non-header view
    // 'section' is section index
    // 'relativePosition' is index in this section
    // 'absolutePosition' is index out of all non-header items

    // Get model based on item view position
    CacheEntry cacheEntryModel = entries.get(absolutePosition);

    // Fill item view with data from model
    viewHolder.title.setText(cacheEntryModel.getTitle());
    viewHolder.size.setText(cacheEntryModel.getFormattedCacheSize());
    viewHolder.icon.setImageDrawable(cacheEntryModel.getIcon());
    viewHolder.cb.setChecked(cacheEntryModel.isSelected());

    // Set Selected/Unselected OnClick listener
    viewHolder.cb.setOnClickListener(v -> cacheEntryModel.setSelected(viewHolder.cb.isChecked()));
}
```

```java
06-09 08:29:26.554 3722-3722/io.github.madeinspengergasse.wischmopp D/AndroidRuntime: Shutting down VM
06-09 08:29:26.554 3722-3722/io.github.madeinspengergasse.wischmopp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                      Process: io.github.madeinspengergasse.wischmopp, PID: 3722
                                                                                      java.lang.IndexOutOfBoundsException: Index: 84, Size: 84
                                                                                          at java.util.ArrayList.get(ArrayList.java:411)
                                                                                          at io.github.madeinspengergasse.wischmopp.util.CompositeUnmodifiableList.get(CompositeUnmodifiableList.java:29)
                                                                                          at io.github.madeinspengergasse.wischmopp.scan.view.CacheEntriesAdapter.onBindViewHolder(CacheEntriesAdapter.java:83)
                                                                                          at io.github.madeinspengergasse.wischmopp.scan.view.CacheEntriesAdapter.onBindViewHolder(CacheEntriesAdapter.java:22)
                                                                                          at com.afollestad.sectionedrecyclerview.SectionedRecyclerViewAdapter.onBindViewHolder(SectionedRecyclerViewAdapter.java:258)
                                                                                          at com.afollestad.sectionedrecyclerview.SectionedRecyclerViewAdapter.onBindViewHolder(SectionedRecyclerViewAdapter.java:17)
                                                                                          at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                                                          at com.afollestad.sectionedrecyclerview.SectionedRecyclerViewAdapter.onBindViewHolder(SectionedRecyclerViewAdapter.java:278)
                                                                                          at com.afollestad.sectionedrecyclerview.SectionedRecyclerViewAdapter.onBindViewHolder(SectionedRecyclerViewAdapter.java:17)
                                                                                          at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                                          at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                                          at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                                          at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:282)
                                                                                          at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:336)
                                                                                          at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:349)
                                                                                          at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:356)
                                                                                          at android.support.v7.widget.GapWorker.run(GapWorker.java:387)
                                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

The current project state can be found [here](https://github.com/Xorok/Wischmopp/tree/testing/adrian), and the affected file is [CacheEntriesAdapter](https://github.com/Xorok/Wischmopp/blob/testing/adrian/app/src/main/java/io/github/madeinspengergasse/wischmopp/scan/view/CacheEntriesAdapter.java) again.
 
###### Reproduction Steps

1. Make a big list and use it as data for the adapter
2. Scroll down in the UI until the bottom

###### Expected Result
absolutePosition stays within the bounds of the entries list and can safely be used to instantiate views based on the model data.

###### Actual Result
absolutePosition grows bigger than the max index of the list.

**Comment by afollestad** [comment]
Absolute position takes the headers into account as seen in this picture:

<img src="https://raw.githubusercontent.com/afollestad/sectioned-recyclerview/master/art/showcase2.png" width="400" />

**Comment by afollestad** [comment]
So I'm guessing you're using one single dataset and getting items with the absolute position, rather than getting items per section

**Comment by afollestad** [comment]
Generally what's intended for structuring data is:

```java
Map<Integer, List<Object>> dataSet = // ...

int getSectionCount() {
    return dataSet.size();
}

int getItemCount(int section) {
    return dataSet.get(section).size();
}

void onBindViewHolder(ViewHolder holder, int section, int relative, int absolute) {
    Object item = dataSet.get(section).get(relative);
    ...
}
```

**Comment by Xorok** [comment]
Ah, okay. Strange that this worked in v0.4.1.

Shouldn't the description of absolutePosition in onBindViewHolder rather be `// 'absolutePosition' is index including header items.` than `// 'absolutePosition' is index out of all non-header items`? I understood the current description as absolutePosition being the absolute index excluding the section headers.
