### ISSUE TITLE
[Help] erro using notifyItemRemoved() on delete the last item of a section

### ISSUE THREAD

**Issue by LipeDuoli** [afollestad/sectioned-recyclerview#50]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of this library.
- [x] I have given my issue a non-generic title.

###### Include the following:
 - Library version: `0.5.0`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Android Emulator`
 - Device Name: `Nexus 5X`

I have a `ItemTouchHelper` on my recyclerview with left swipe to delete an item from my list(delete only itens of a section, not directly a section). After remove an Item from the list I use `notifyItemRemoved(absolutePosition)` to remove the view from the adapter. Everything works fine if I have several itens on a section, but when I try remove the last item of a section i get this error

```java
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{a3bace8 position=0 id=-1, oldPos=0, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}
    at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5297)
    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5479)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3534)
    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3310)
    at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1648)
    at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:343)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
    at android.view.Choreographer.doCallbacks(Choreographer.java:686)
    at android.view.Choreographer.doFrame(Choreographer.java:618)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6119)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

If I change the `notifyItemRemoved()` to `notifyDataSetChanged()` everything works fine, the last item are remove without any error and the section hide because is empty.
 
###### Reproduction Steps

1. get a adapter with at least 1 section with several itens
2. create a function to remove an item from a list of that section and call `notifyItemRemoved(absolutePosition)`
3. remove the last item of that section

###### Expected Result

Remove the item and hide the section

###### Actual Result

Error described above

**Comment by AkshayChordiya** [comment]
I tested `notifyItemRemoved(int absolutePosition)` and it works perfect for me.  @LipeDuoli Maybe there is some issue with your code implementation.

**Comment by LipeDuoli** [comment]
In my case, if I try remove all itens on any section I create the app crash

**Comment by AkshayChordiya** [comment]
@afollestad Any updates on fixing this issue?

**Comment by asadtariq96** [comment]
facing same issue.

**Comment by abbasalim** [comment]
:(
